name: Deploys

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'type'
        required: true

jobs:
  config:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: get config
        run: |
          echo "Get configuration file"

  deploy-cloudflare:
    needs: config
    if: contains(github.event.inputs.type, 'cloudflare')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done

  deploy-s3:
    needs: config
    if: contains(github.event.inputs.type, 's3')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
