name: Deploys

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'type'
        required: true

jobs:
  deploy-cloudflare:
    if: contains(github.event.inputs.type, 'cloudflare')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

  deploy-s3:
    if: contains(github.event.inputs.type, 's3')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
