name: Tests

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'type'
        required: true

jobs:
  tests:
    runs-on: ubuntu-20.04

     steps:
      - uses: actions/checkout@v2
